services:
  mysql:
    image: mysql:5.7
    container_name: users_mysql
    environment:
      MYSQL_ROOT_PASSWORD: supposed-to-be-secret
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    networks:
      - auth-network

  auth-service:
    build: ./backend/auth-service
    container_name: auth_service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://users_mysql:3306/users_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: supposed-to-be-secret
      SPRING_CONFIG_ADDITIONAL_LOCATION: /config/external.properties
    volumes:
      - ~/Documentos/external.properties:/config/external.properties
      - /app/profile-photos
    networks:
      - auth-network

  posts-service:
    build: ./backend/posts-service
    container_name: posts_service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://users_mysql:3306/users_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: supposed-to-be-secret
      SPRING_CONFIG_ADDITIONAL_LOCATION: /config/external.properties
    volumes:
      - ~/Documentos/external.properties:/config/external.properties
    networks:
      - auth-network

  api-gateway:
    build: ./backend/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - posts-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      POSTS_SERVICE_URL: http://posts-service:8082
    networks:
      - auth-network

  #frontend:
  #  build: ./frontend
  #  container_name: frontend
  #  ports:
  #    - "3000:3000"
  #  networks:
  #    - auth-network

networks:
  auth-network:
    driver: bridge
