services:
  mysql:
    image: mysql:5.7
    container_name: auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    networks:
      - auth-network

  auth-service:
    build: ./backend/auth-service
    container_name: auth_service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth_mysql:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yourpassword
    networks:
      - auth-network

  api-gateway:
    build: ./backend/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

